version: 2

models:
  - name: dim_tag
    columns:
      - name: tag_key
        tests: [not_null, unique]

  - name: dim_date
    columns:
      - name: date_key
        tests: [not_null, unique]

  - name: dim_user
    columns:
      - name: user_id
        tests: [not_null, unique]

  - name: fact_question_day_tag_tbl
    columns:
      - name: date
        tests: [not_null]
      - name: tag_key
        tests: [not_null]
